// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFyARTe5htvFenm-AwoVUOES3iwce8sjM',
    appId: '1:327324836622:web:252e7906b04fde8136ad5f',
    messagingSenderId: '327324836622',
    projectId: 'eshop-multivendor-new',
    authDomain: 'eshop-multivendor-new.firebaseapp.com',
    storageBucket: 'eshop-multivendor-new.appspot.com',
    measurementId: 'G-J7Y3R8EJPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZKq2UF70TLpf1uhBpvlwV-mZXTlb38oE',
    appId: '1:296741108859:android:62241da5053448d08d36de',
    messagingSenderId: '296741108859',
    projectId: 'halanurapp',
    storageBucket: 'halanurapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnmfpSNHmMo16Ni50QgljjvjF3IKIG_d8',
    appId: '1:296741108859:ios:e26b634dbac5762e8d36de',
    messagingSenderId: '296741108859',
    projectId: 'halanurapp',
    storageBucket: 'halanurapp.firebasestorage.app',
    androidClientId: '296741108859-3n09fn1dvotfo0c9gsvdicroujmje38u.apps.googleusercontent.com',
    iosClientId: '296741108859-v74pfrn55jvmq9v6hmb96eja269jrvkk.apps.googleusercontent.com',
    iosBundleId: 'org.halanur.halanur',
  );

}